add_newline = false

[aws]
format = 'î˜¡ [$symbol($profile)(\($region\))(\[$duration\])]($style) '

[cmake]
format = 'î˜¡ [$symbol($version)]($style) '

[cmd_duration]
format = 'î˜¡ [â± $duration ]($style) '

[cobol]
format = 'î˜¡ [$symbol($version)]($style) '

[conda]
format = 'î˜¡ [$symbol$environment]($style) '

[crystal]
format = 'î˜¡ [$symbol($version)]($style) '

[dart]
format = 'î˜¡ [$symbol($version)]($style) '

[deno]
format = 'î˜¡ [$symbol($version)]($style) '

[docker_context]
format = 'î˜¡ [$symbol$context]($style) '

[dotnet]
format = 'î˜¡ [$symbol($version)(ğŸ¯ $tfm)]($style) '

[elixir]
format = 'î˜¡ [$symbol($version \(OTP $otp_version\))]($style) '

[elm]
format = 'î˜¡ [$symbol($version)]($style) '
symbol = "î˜¬ "

[erlang]
format = 'î˜¡ [$symbol($version)]($style) '

[gcloud]
format = 'î˜¡ [$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
format = 'î˜¡ [$symbol$branch]($style) '

[git_status]
format = '(î˜¡ [$all_status$ahead_behind]($style) )'

[golang]
format = 'î˜¡ [$symbol($version)]($style) '

[helm]
format = 'î˜¡ [$symbol($version)]($style) '

[hg_branch]
format = 'î˜¡ [$symbol$branch]($style) '

[java]
format = 'î˜¡ [$symbol($version)]($style) '

[julia]
format = 'î˜¡ [$symbol($version)]($style) '

[kotlin]
format = 'î˜¡ [$symbol($version)]($style) '

[kubernetes]
format = 'î˜¡ [$symbol$context( \($namespace\))]($style) '

[lua]
format = 'î˜¡ [$symbol($version)]($style) '

[memory_usage]
format = 'î˜¡ $symbol[$ram( | $swap)]($style) '

[nim]
format = 'î˜¡ [$symbol($version)]($style) '

[nix_shell]
format = 'î˜¡ [$symbol$state( \($name\))]($style) '

[nodejs]
format = 'î˜¡ [$symbol($version)]($style) '

[ocaml]
format = 'î˜¡ [$symbol($version)(\($switch_indicator$switch_name\))]($style) '

[openstack]
format = 'î˜¡ [$symbol$cloud(\($project\))]($style) '

[package]
format = 'î˜¡ [$symbol$version]($style) '

[perl]
format = 'î˜¡ [$symbol($version)]($style) '

[php]
format = 'î˜¡ [$symbol($version)]($style) '

[pulumi]
format = 'î˜¡ [$symbol$stack]($style) '

[purescript]
format = 'î˜¡ [$symbol($version)]($style) '

[python]
format = 'î˜¡ [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol = 'ï Ÿ '

[red]
format = 'î˜¡ [$symbol($version)]($style) '

[ruby]
format = 'î˜¡ [$symbol($version)]($style) '

[rust]
format = 'î˜¡ [$symbol($version)]($style) '

[scala]
format = 'î˜¡ [$symbol($version)]($style) '

[swift]
format = 'î˜¡ [$symbol($version)]($style) '

[terraform]
format = 'î˜¡ [$symbol$workspace]($style) '

[time]
format = 'î˜¡ [$time]($style) '

[username]
format = 'î˜¡ [$user]($style) '

[vagrant]
format = 'î˜¡ [$symbol($version)]($style) '

[vlang]
format = 'î˜¡ [$symbol($version)]($style) '

[zig]
format = 'î˜¡ [$symbol($version)]($style) '
